### ISSUE TITLE
Package not working on OpenWRT v22.03?; previous v21.02 worked ok

### ISSUE THREAD

**Issue by malkovich78** [onemarcfifty/luci-proto-batman-adv#2]
Hi Marc,

Thanks for you excellent work; this package worked perfectly on previous stable version 21.02 but it seems on new stable version 22.03 there are some changes so it doesn't work any more, please take a look when you have some time. 

Regards.

**Comment by onemarcfifty** [comment]
Thanks for the heads up. I'll update my systems soon and see if it works and what needs to be fixed.

**Comment by malkovich78** [comment]
Hi again,

It seems the error I reported is related to an installation mistake or a missing dependency and not a package one.

I tried on different devices and the package works ok after upgrading to OpenWRT v22.03; I tried again on the previous device giving the error with a fresh OpenWRT v22.03 installation and after following the right pkg installation order and making sure all pkg dependencies were satisfied everything worked as expected.

Regards.
